# chatbot.py

def chatbot_response(user_input):

    user_input = user_input.lower()


    if "hello" in user_input or "hi" in user_input:
        return "Hello! How can I help you today?"
    elif "bye" in user_input or "goodbye" in user_input:
        return "Goodbye! Have a great day!"
    elif "how are you" in user_input:
        return "I'm just a bot, but I'm doing great! How about you?"
    elif "what is your name" in user_input:
        return "This is Kisu Bot , Generated By Kiran"
    elif "how was the wheather" in user_input:
        return "I can't Visualize real scenary"
    elif "your name" in user_input:
        return "I'm a simple rule-based chatbot created by Kiran."
    elif "help" in user_input:
        return "I'm here to assist you. You can ask me about general topics."
    elif "time" in user_input:
        from datetime import datetime
        now = datetime.now()
        return f"The current time is {now.strftime('%H:%M:%S')}."
    elif "date" in user_input:
        from datetime import datetime
        today = datetime.today()
        return f"Today's date is {today.strftime('%Y-%m-%d')}."
    else:
        return "I'm sorry, I don't understand Your Query"

def main():
    print("Welcome to the Rule-Based Chatbot Creted By Kiran . Type 'exit' to end the conversation.")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'exit':
            print("Chatbot: Goodbye ! ,Have a Nice day !")
            break
        response = chatbot_response(user_input)
        print("Chatbot:", response)

if __name__ == "__main__":
    main()
